spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://share-db:5432/auth-service-db
    username: share
    password: share
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
logging.level:
  org:
    springframework.security: DEBUG

server:
  port: 8001
  forward-headers-strategy: framework
  servlet:
    context-path: /auth
springdoc:
  swagger-ui:
    path: /docs
  show-oauth2-endpoints: true