
server:
  port: 9002

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/



management:
  endpoints:
    web:
      exposure:
        include: "*"

