apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-svc
  template:
    metadata:
      labels:
        app: user-svc
    spec:
      imagePullSecrets:
        - name: ghcr.io-secret
      containers:
        - name: auth-svc
          image: ghcr.io/ngodat0103/user-svc:pr-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8002