apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - image: registry-harbor.ngodat0103.me/kltn/auth-service
          name: auth
          securityContext:
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 7001