spring:
  profiles:
    default: local-dev
  config:
    import:
      - "optional:local-dev.yaml"
      - "optional:docker-dev.yaml"
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8001
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service
          uri: http://user-service:8002
          predicates:
            - Path=/api/v1/user/**
server:
  port: 8000
management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      enabled: true