spring:
  profiles:
    active: local-dev
  config:
    import:
      - "optional:local-dev.yaml"
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8001
          predicates:
            - Path=/api/v1/auth/**
#          filters:
#            - CircuitBreaker=auth-service-breaker
        - id: user-service
          uri: http://user-service:8002
          predicates:
            - Path=/api/v1/user/**
#          filters:
#            - CircuitBreaker=user-service-breaker
server:
  port: 8000
  reactive:
    session:
      cookie:
        name: SESSION
        domain: localhost
management:
  endpoints:
    web:
      exposure:
        include: gateway,circuitbreakers
  endpoint:
    gateway:
      enabled: true