spring:

  security:
    oauth2:
      client:
        provider:
          auth-service:
            authorization-uri: http://auth-service:8001/api/v1/auth/oauth2/authorize
            token-uri: http://auth-service:8001/api/v1/auth/oauth2/token
        registration:
          gateway-service:
            provider: auth-service
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic
            client-id: gateway-service
            client-secret: "{cipher}806472b06e24fc5a178e34594f1c6406cc662fb95c63596dece4d03e10bd8ee6ba014c5d22f5b13ce206544f3cbb2e20"
            scope: auth-service.read


  config:
    activate:
      on-profile: local-dev
  data:
    redis:
      url: redis://redis-service:6379
      client-type: lettuce
      database: 0
      client-name: gateway-service
logging:
  level:
    com.example.gateway.filter: DEBUG
    org.springframework.security: DEBUG


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /ui-docs
    enabled: true
    oauth:
      client-id: swagger-client
      client-secret: "{cipher}dcbe3d737b10508e19c95bf72cfe2d22b734104965350a20d6297ebed9953bdfabd761772530e5bb6c2fbc7e30d64551"
      use-basic-authentication-with-access-code-grant: true
    oauth2-redirect-url: http://localhost:8000/webjars/swagger-ui/oauth2-redirect.html
    urls:
      - name: "auth-service"
        url: "http://localhost:8000/api/v1/auth/api-docs"
      - name: "user-service"
        url: "http://localhost:8000/api/v1/user/api-docs"
    use-root-path: true
