spring:
  profiles:
    default: local-dev
  config:
    import:
      - "optional:unit-test.yaml"
      - "optional:local-dev.yaml"
      - "optional:demo.yaml"
  application:
    name: auth-service
server:
  port: 8001
  forward-headers-strategy: framework
  servlet:
    context-path: /api/v1/auth
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /ui-docs
  open-api:
    info:
      version: 1.0.0
      title: Auth Service
      description: Auth Service API
      contact:
        name: NgoDat0103
        url: https://github.com/NGODAT0103
        email: 21521935@gm.uit.edu.vn