spring:
  profiles:
    default: local-dev
  config:
    import:
      - "optional:unit-test.yaml"
      - "optional:local-dev.yaml"
      - "optional:demo.yaml"
      - "optional:integration-test.yaml"
      - "optional:pre-proc.yaml"
  application:
    name: auth-svc
  data:
    redis:
      url: redis://redis-svc:6379
      client-name: auth-svc
server:
  port: 8001
  forward-headers-strategy: framework
  servlet:
    context-path: /api/v1/auth
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /ui-docs
  open-api:
    info:
      version: 1.0.0
      title: Auth Service
      description: Auth Service API
      contact:
        name: NgoDat0103
        url: https://github.com/NGODAT0103
        email: 21521935@gm.uit.edu.vn
  show-login-endpoint: true
  show-actuator: true

logging:
  level:
    com.github.ngodat0103.yamp.authsvc.service: DEBUG
    com.github.ngodat0103.yamp.authsvc.controller: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"