spring:
  config:
    activate:
      on-profile: demo
  datasource:
    url: jdbc:postgresql://share-db:5432/auth-svc-db
    username: 'auth-svc-user'
    password: 'auth-svc-user-password'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      url: redis://redis-svc:6379
      client-name: auth-service
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8000/api/v1/auth
logging:
  level:
    com.github.ngodat0103.yamp.authsvc.service: DEBUG
    com.github.ngodat0103.yamp.authsvc.controller: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always