spring:
  cloud:
    inetutils:
      default-hostname: "localhost"
  config:
    activate:
      on-profile: local-dev
  datasource:
    url: jdbc:postgresql://share-db:5432/auth-svc-db
    username: 'auth-svc-user'
    password: '{cipher}e4b0a2a815e34f4e3ad39d30b1fbdffd994ce5695fb5976b370b9965d8d117f548b1303da957eb20c4865c3c3c0276b0'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      url: redis://redis-svc:6379
      client-name: auth-service
  security:
    oauth2:
      authorizationserver:
        issuer: http://${spring.cloud.inetutils.default-hostname}:8000/api/v1/auth
logging:
  level:
    com.github.ngodat0103.yamp.authsvc.service: DEBUG
    com.github.ngodat0103.yamp.authsvc.controller: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always