spring:
  cloud:
    inetutils:
      default-hostname: yamp-backend.ngodat0103.live
  config:
    activate:
      on-profile: pre-proc
  datasource:
    url: jdbc:postgresql://share-db:5432/auth-svc-db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      authorizationserver:
        issuer: http://${spring.cloud.inetutils.default-hostname}/api/v1/auth


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
