spring:
  cloud:
    inetutils:
      default-hostname: yamp-backend.ngodat0103.live
  config:
    activate:
      on-profile: pre-prod
  datasource:
    url: jdbc:postgresql://share-db:5432/auth-svc-db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        provider:
          auth-service-external:
            authorization-uri: http://${spring.cloud.inetutils.default-hostname}/api/v1/auth/oauth2/authorize
            token-uri: http://${spring.cloud.inetutils.default-hostname}/api/v1/auth/oauth2/token
            jwk-set-uri: http://${spring.cloud.inetutils.default-hostname}/api/v1/auth/oauth2/jwks
      authorizationserver:
        issuer: http://${spring.cloud.inetutils.default-hostname}/api/v1/auth

