spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://share-db:5432/test
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    redis:
      database: 3
      host: redis-svc
      client-name: auth-svc
      client-type: lettuce
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8000/api/v1/auth
      client:
        provider:
          hcp-vault-provider:
            token-uri: https://auth.idp.hashicorp.com/oauth2/token
        registration:
          hcp-vault-client:
            client-authentication-method: client_secret_basic
            authorization-grant-type: "client_credentials"
            provider: hcp-vault-provider
            client-id: "{cipher}5127dc6c6f3048cb9915341aabe36094e96d4a70785eacfe444fc5476e0d9c67f7a6b91237fc47ef600c5a5ba6e3441d1e5d0d96d23238ef78c88d8071da8bdd"
            client-secret: "{cipher}261d1370f6c91ca84e624ab0d1e991fcddc9b973603393b46600b344211f40eb687e87192b0cdb5db32d7bad9dae85274c88a5a5e3c5738fe94d777f524a9e30f22c5aaa4861cf179202f96bd53d3ea63a679830e966e249b26d0a92e4b85ed3"

hcp-vault:
  jwk-secret-path: https://api.cloud.hashicorp.com/secrets/2023-06-13/organizations/cbe1cf74-4825-4a1b-8c63-c685c98f813c/projects/d0064e9e-e611-4d22-8151-d54a515c513d/apps/authTZ/open
