spring:
  datasource:
    url: jdbc:postgresql://share-db:5432/user-service-db
    username: share
    password: share
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:

      ddl-auto:  create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

springdoc:
  swagger-ui:
    path: /ui-docs
    oauth:
      client-id: webclient
      client-secret: webclientsecret
      use-basic-authentication-with-access-code-grant: true
    oauth2-redirect-url: http://localhost:8000/ui-docs/swagger-ui/oauth2-redirect.html
  api-docs:
    path: /api-docs


