spring:
  config:
    activate:
      on-profile: docker-dev
  datasource:
    url: jdbc:postgresql://share-db:5432/user-service-db
    username: "{cipher}8d5408ba942dc178a167f8b27a52f866184a2c084d21b713f6904932d2963285"
    password: "{cipher}8d5408ba942dc178a167f8b27a52f866184a2c084d21b713f6904932d2963285"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:

      ddl-auto:  create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true



