spring:
  security:
    oauth2:
      client:
        registration:
          user-service:
            provider: auth-service
            client-id: user-service
            client-secret: user-service-secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            scope:
              - auth-service.read
              - auth-service.write
        provider:
          auth-service:
            token-uri: http://gateway-service:8000/api/v1/auth/oauth2/token
            authorization-uri: http://gateway-service:8000/api/v1/auth/oauth2/authorize
  datasource:
    url: jdbc:postgresql://share-db:5432/user-service-db
    username: share
    password: share
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:

      ddl-auto:  create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
springdoc:
  swagger-ui:
    path: /ui-docs
    oauth:
      client-id: webclient
      client-secret: webclientsecret
      use-basic-authentication-with-access-code-grant: true
    oauth2-redirect-url: http://localhost:8000/ui-docs/swagger-ui/oauth2-redirect.html
  api-docs:
    path: /api-docs
logging:
  level:
    org.springframework.security: DEBUG

