spring:
  profiles:
    active: local-dev
  config:
    import:
      - "optional:local-dev.yaml"
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-svc:8001
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: auth-service-breaker
                fallbackUri: forward:/fallback/auth-svc
        - id: user-service
          uri: http://user-svc:8002
          predicates:
            - Path=/api/v1/user/**
#          filters:
#            - CircuitBreaker=user-service-breaker
server:
  port: 8000
management:
  endpoints:
    web:
      exposure:
        include: gateway,circuitbreakers
  endpoint:
    gateway:
      enabled: true