spring:
  profiles:
    active: local-dev
    default: local-dev
  config:
    import:
      - "optional:local-dev.yaml"
      - "optional:unit-test.yaml"
      - "optional:demo.yaml"
      - "optional:integration-test.yaml"
      - "optional:pre-proc.yaml"
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-svc
          uri: http://auth-svc:8001
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: auth-service-breaker
                fallbackUri: forward:/fallback/auth-svc
        - id: user-svc
          uri: http://user-svc:8002
          predicates:
            - Path=/api/v1/user/**
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 1
#                redis-rate-limiter.requestedTokens: 1
#            - name: Retry
#              args:
#                method: GET
#                backoff:
#                  firstBackoff: 100ms
#                  maxBackoff: 1000ms
#                  factor: 2
#            - name: CircuitBreaker
#              args:
#                name: user-service-breaker
#                fallbackUri: forward:/fallback
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
server:
  port: 8000
management:
  endpoints:
    web:
      exposure:
        include: gateway,circuitbreakers
  endpoint:
    gateway:
      enabled: true