spring:
  config:
    activate:
      on-profile: pre-proc
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
    inetutils:
      default-hostname: yamp-backend.ngodat0103.live

#  security:
#    oauth2:
#      client:
#        provider:
#          auth-service:
#            authorization-uri: http://${spring.cloud.inetutils.default-hostname}:8000/api/v1/auth/oauth2/authorize
#            token-uri: http://${spring.cloud.inetutils.default-hostname}:8000/api/v1/auth/oauth2/token
#            jwk-set-uri: http://auth-svc:8001/api/v1/auth/oauth2/jwks
#        registration:
#          gateway-service:
#            redirect-uri: "http://${spring.cloud.inetutils.default-hostname}:8000/login/oauth2/code/gateway-service"
#            provider: auth-service
#            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_basic
#            scope: user.read,openid,profile,message.read,message.write




