spring:
  profiles:
    default: local-dev
  config:
    import:
      - "optional:local-dev.yaml"
      - "optional:unit-test.yaml"
      - "optional:demo.yaml"
      - "optional:integration-test.yaml"
      - "optional:pre-proc.yaml"
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-svc:8001/api/v1/auth/oauth2/jwks
          authorities-claim-name: "roles"
          authority-prefix: "ROLE_"
server:
  port: 8002
  forward-headers-strategy: framework
  servlet:
    encoding:
      enabled: false
    context-path: /api/v1/user

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /ui-docs
  open-api:
    info:
      version: 1.0.0
      title: User Service
      description: User Service API
      contact:
        name: NgoDat0103
        url: https://github.com/NGODAT0103
        email: 21521935@gm.uit.edu.vn