spring:
  profiles:
    default: local-dev
  config:
    import:
      - "optional:local-dev.yaml"
      - "optional:docker-dev.yaml"
      - "optional:unit-test.yaml"
  application:
    name: user-service
server:
  port: 8002
  forward-headers-strategy: framework
  servlet:
    encoding:
      enabled: false
    context-path: /api/v1/user

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /ui-docs
  open-api:
    info:
      version: 1.0.0
      title: User Service
      description: User Service API
      contact:
        name: NgoDat0103
        url: https://github.com/NGODAT0103
        email: 21521935@gm.uit.edu.vn