spring:
  config:
    activate:
      on-profile: local-dev
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-svc:8001/api/v1/auth/oauth2/jwks

  datasource:
    url: jdbc:postgresql://share-db:5432/user-svc-db
    username: 'user-svc-user'
    password: '{cipher}0579337b871cd41ba98c4875971fa8eca89a6a6902e15b6cf75f711c299912285e825d81331fa61ec4317b6306c3b29d'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto:  update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
#logging:
#  level:
#    org.springframework.security: DEBUG
#    com.example.userservice.security: DEBUG
#    com.example.userservice.exception: ERROR
#    com.example.userservice.service: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
