spring:
  profiles:
    default: dev-local
  config:
    import:
      - 'optional:classpath:/dev-local.yaml'
      - 'optional:test.yaml'
      - "optional:integration-test.yaml"
  application:
    name: product-svc
server:
  port: 8003