on:
  push:
    branches:
      - "feature/**"
    paths:
      - "auth-svc/**"
  pull_request:
    branches:
      - "feature/**"
      - "Fix**"
    paths:
      - "auth-svc/**"

jobs:
  push:
    name: auth-svc-push
    if: github.event_name == 'push'
    uses: ./.github/workflows/ci-push-workflow-call.yaml
    with:
      SERVICE_NAME: auth-svc
      SERVICE_PORT: 8001
    secrets: inherit
  pr-integration-test:
    name: auth-svc-integration-test
    if: github.event_name == 'pull_request'
    runs-on: cloud-uit
    services:
      redis-svc:
        image: redis:6.2.6
      share-db:
        image: postgres:16.3-bullseye
        volumes:
          - /home/github-runner/yamp-integration/init.sql:/docker-entrypoint-initdb.d/init.sql
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    container:
      image: maven:3.8.4-openjdk-17
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Cache Maven packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-v1-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-v1-
      - name: Running integration test
        working-directory: auth-svc
        env:
          ENCRYPT_KEY: ${{secrets.ENCRYPT_KEY}}
        run: mvn test -q -Dtest=*IntegrationTest
  pr-push-image:
    name: auth-svc-pr-push-image
    if: github.event_name == 'pull_request'
    needs: [pr-integration-test]
    uses: ./.github/workflows/ci-pr-workflow-call.yaml
    with:
      SERVICE_NAME: auth-svc
      SERVICE_PORT: 8001
