name: CD reusable workflow
on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        description: "name of the service to trigger the CD"
        required: true
        type: string
      VERSION:
        description: "version of the service to deploy"
        required: true
        type: string
jobs:
  build-ready-container:
    environment: development
    name: build ready container
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up buildx
        uses: docker/setup-buildx-action@v3.4.0
      - name: docker login credential
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{secrets.REGISTRY_URL}}
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}

      - name: read port from service configuration
        id: read-yaml
        uses: jbutcher5/read-yaml@main
        with:
          file: ${{inputs.SERVICE_NAME}}/src/main/resources/application.yaml
          key-path: '["server", "port"]'
      - name: build and push
        uses: docker/build-push-action@v6.4.0
        with:
          context: ${{inputs.SERVICE_NAME}}
          file: Dockerfile
          push: true
          tags: ${{secrets.REGISTRY_URL}}/kltn/${{inputs.SERVICE_NAME}}:${{inputs.VERSION}}-dev}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: SERVICE_NAME=${{inputs.SERVICE_NAME}},SERVICE_PORT=${{steps.read-yaml.outputs.data}}