name: ci-workflow
on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        description: "name of the service to trigger the CI"
        required: true
        type: string
      SERVICE_PORT:
        description: "port of the service to trigger the CI"
        required: true
        type: string
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.8-eclipse-temurin-17-alpine
    services:
      share-db:
        image: postgres:16.3-bullseye
        env:
          POSTGRES_USER: share
          POSTGRES_PASSWORD: share
          POSTGRES_DB: ${{inputs.SERVICE_NAME}}-db
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: set up cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Running test
        working-directory: ${{inputs.SERVICE_NAME}}
        run: mvn test


  scan_quality_code:
    name: Scan quality
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache SonarQube packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        working-directory: ${{inputs.SERVICE_NAME}}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=NGODAT0103_KLTN_469d6be5-1cc8-4567-ae29-7f3f9dc29ff6 -Dsonar.projectName='KLTN'

  scan_security:
    name: Security check
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: snyk setup
        uses: snyk/actions/setup@master
      - name: java set up
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: snky test
        working-directory: ${{inputs.SERVICE_NAME}}
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
        run: |
          chmod +x ./mvnw
          snyk test

  scan_vulnerability:
    name: check vulnerability
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy
      - name: set up trivy
        run: | 
          wget https://github.com/aquasecurity/trivy/releases/download/v0.53.0/trivy_0.53.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.53.0_Linux-64bit.deb
      - name: trivy scan
        working-directory: ${{inputs.SERVICE_NAME}}
        env:
          TRIVY_USERNAME: ${{github.repository_owner}}
          TRIVY_PASSWORD: ${{github.token}}
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .
  scan_misconfig:
    name: check misconfiguration
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up cache trivy
        uses: actions/cache@v4.0.2
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy
      - name: set up trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.53.0/trivy_0.53.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.53.0_Linux-64bit.deb
      - name: trivy scan
        working-directory: ${{inputs.SERVICE_NAME}}
        env:
          TRIVY_USERNAME: ${{github.repository_owner}}
          TRIVY_PASSWORD: ${{secrets.GITHUB_TOKEN}}
        run: trivy fs --scanners misconfig --exit-code 1 --severity HIGH,CRITICAL .

  build-and-push:
    permissions:
      contents: read
      packages: write
    needs: [ test,scan_security,scan_vulnerability,scan_misconfig]
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up buildx
        uses: docker/setup-buildx-action@v3.4.0
      - name: docker login credential
        uses: docker/login-action@v3.2.0
        with:
          logout: false
          registry: ${{secrets.REGISTRY_URL}}
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}


      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{secrets.REGISTRY_URL}}/ngodat0103/kltn/${{inputs.SERVICE_NAME}}
      - name: build and push
        uses: docker/build-push-action@v6.3.0
        with:
          context: ${{inputs.SERVICE_NAME}}
          file: Dockerfile-For-CI
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
          build-args: |
            SERVICE_NAME=${{inputs.SERVICE_NAME}}
            SERVICE_PORT=${{inputs.SERVICE_PORT}}

  security_check:
    name: Security check for docker image
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Scan security
        id: generate-report
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{secrets.REGISTRY_URL}}/kltn/${{inputs.SERVICE_NAME}}:${{github.sha}}
          severity: HIGH,CRITICAL
          vuln-type: os,library
          exit-code: 1
          format: template
          template: '@/contrib/html.tpl'
          output: ${{inputs.SERVICE_NAME}}-report-${{github.sha}}.html
        env:
          TRIVY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
          TRIVY_PASSWORD: ${{secrets.GITHUB_TOKEN}}
      - name: Upload ${{inputs.SERVICE_NAME}} security report to artifact tab
        if: ${{steps.generate-report.conclusion == 'failure'}}
        uses: actions/upload-artifact@v4.3.4
        with:
          name: ${{inputs.SERVICE_NAME}}-report-${{github.sha}}.html
          if-no-files-found: warn
          path: ${{inputs.SERVICE_NAME}}-report-${{github.sha}}.html

