name: CI
on:
  push:
    paths:
      - "user-service/**"
      - '.github/workflows/**'
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{steps.get_changed.outputs.changed}}
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set changes
          uses: Stockopedia/action-get-changed-files@v2
          id: get_changed
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            ignore: "**/+(.github)"
            format: "csv"
            foldersOnly: true # to only include folders in the output
        - name: Echo
          run: echo ${{ steps.get_changed.outputs.changed }}


  user-service-build-and-push:
    needs: detect-changes
    runs-on: home
    if: contains(needs.detect-changes.outputs.changed,'user-service') == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{secrets.REGISTRY_URL}}
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}
      - name: build
        run: docker compose build user-service
      - name: push
        run: docker compose push user-service


