name: CI
on:
  push:
    paths:
      - "user-service/**"
      - '.github/workflows/**'
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{steps.get_changed.outputs.changed}}
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set changes
          uses: Stockopedia/action-get-changed-files@v2
          id: get_changed
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            ignore: "**/+(.github)"
            format: "csv"
            foldersOnly: true # to only include folders in the output
        - name: Echo
          run: echo ${{ steps.get_changed.outputs.changed }}


  user-service-build-and-push:
    needs: detect-changes
    runs-on: home
    if: ${{contains(needs.detect-changes.outputs.changed,'user-service')}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{secrets.REGISTRY_URL}}
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}
      - name: set up env
        run: |
          touch .env
          echo REGISTRY_URL=${{secrets.REGISTRY_URL}} >> .env
          echo PROJECT_NAME=kltn >> .env
          echo USER_SERVICE_TAG=${{github.sha}} >> .env 
          echo 'USER_SERVICE_IMAGE=${REGISTRY_URL}/${PROJECT_NAME}/user-service:${USER_SERVICE_TAG}' >> .env
          echo 'USER_SERVICE_JAR_FILE=user-service-${USER_SERVICE_TAG}.jar' >> .env

      - name: test .env
        run: cat .env
      - name: build
        run: docker compose build user-service --quiet
      - name: push
        run: docker compose push user-service --quiet
  debug:
    runs-on: ubuntu-latest
    needs: detect-changes
    steps:
      - name: log
        run: |
          echo ${{needs.detect-changes.outputs.changed}}
          echo ${{contains(needs.detect-changes.outputs.changed,'user-service')}}


