name: CI
on:
  push:
    paths:
      - "user-service/**"
      - '.github/workflows/**'
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{steps.get_changed.outputs.changed}}
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set changes
          uses: Stockopedia/action-get-changed-files@v2
          id: get_changed
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            ignore: "**/+(.github)"
            format: "csv"
            foldersOnly: true # to only include folders in the output

  build-and-push:
    needs: detect-changes
    runs-on: home
    if: ${{contains(needs.detect-changes.outputs.changed,'user-service')}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{secrets.REGISTRY_URL}}
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}
      - name: set up env
        run: |
          touch .env
          echo REGISTRY_URL=${{secrets.REGISTRY_URL}} >> .env
          echo PROJECT_NAME=kltn >> .env
          echo USER_SERVICE_TAG=${{github.sha}} >> .env 
          echo 'USER_SERVICE_IMAGE=${REGISTRY_URL}/${PROJECT_NAME}/user-service:${USER_SERVICE_TAG}' >> .env
          echo 'USER_SERVICE_JAR_FILE=user-service-${USER_SERVICE_TAG}.jar' >> .env
      - name: build
        run: docker compose build user-service --quiet
      - name: push
        run: docker compose push user-service --quiet

  security_check:
    runs-on: ubuntu-latest
    needs: [build-and-push,detect-changes]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Scan security for user-service docker image
        if: ${{contains(needs.detect-changes.outputs.changed,'user-service')}}
        id: generate-report
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{secrets.REGISTRY_URL}}/kltn/user-service:${{github.sha}}
          severity: 'HIGH'
          exit-code: 1
          output: user-service-report-${{github.sha}}
        env:
          TRIVY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
          TRIVY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}
      - name: Upload security report to artifact tab
        if: ${{steps.generate-report.outcome == 'success'}}
        uses: actions/upload-artifact@v4.3.4
        with:
          name: user-service-report-${{github.sha}}





  debug:
    runs-on: ubuntu-latest
    needs: detect-changes
    steps:
      - name: log
        run: |
          echo ${{needs.detect-changes.outputs.changed}}
          echo ${{contains(needs.detect-changes.outputs.changed,'user-service')}}


