name: Microservice manual deployment
on:
  workflow_dispatch:
    inputs:
      version:
        description: "version of the service to deploy"
        required: true
        type: string
      gateway-service:
        description: "trigger gateway service deployment"
        type: boolean
      auth-service:
        description: "trigger auth service deployment"
        type: boolean
      user-service:
        description: "trigger user service deployment"
        type: boolean
jobs:
  auth-service-deployment:
    if: ${{ inputs.auth-service == true }}
    uses: ./.github/workflows/cd-reusable-workflow.yaml
    secrets: inherit
    with:
      SERVICE_NAME: auth-service
      VERSION: ${{ github.event.inputs.version }}

