name: reusable_workflow
on:
  workflow_call:
    inputs:
      service_name:
        description: "name of the service to trigger the CI"
        required: true
        type: string
jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up buildx
        uses: docker/setup-buildx-action@v3.4.0
      - name: docker login credential
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{secrets.REGISTRY_URL}}
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}
      - name: build and push
        uses: docker/build-push-action@v6.4.0
        with:
          context: ${{inputs.service_name}}
          file: Dockerfile
          push: true
          tags: ${{secrets.REGISTRY_URL}}/kltn/${{inputs.service_name}}:${{github.sha}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: service_name=${{inputs.service_name}}

  security_check:
    name: Security check for ${{inputs.service_name}}
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Scan security
        id: generate-report
        uses: aquasecurity/trivy-action@0.24.0
        continue-on-error: true
        with:
          image-ref: ${{secrets.REGISTRY_URL}}/kltn/${{inputs.service_name}}:${{github.sha}}
          severity: 'HIGH'
          exit-code: 1
          format: template
          template: '@/usr/local/share/trivy/templates/html.tpl'
          output: ${{inputs.service_name}}-report-${{github.sha}}.html
        env:
          TRIVY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
          TRIVY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}
      - name: Upload ${{inputs.service_name}} security report to artifact tab
        if: always()
        uses: actions/upload-artifact@v4.3.4
        with:
          name: ${{inputs.service_name}}-report-${{github.sha}}.html
          if-no-files-found: warn
          path: ${{inputs.service_name}}-report-${{github.sha}}.html

