name: reusable_workflow
on:
  workflow_call:
    inputs:
      name_service:
        description: "name of the service to trigger the CI"
        required: true
        type: string
jobs:
  build-and-push:
    name: Build and push for ${{inputs.name_service}}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: docker login credential
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{secrets.REGISTRY_URL}}
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}
      - name: build and push for ${{inputs.name_service}}
        uses: docker/build-push-action@v6.4.0
        with:
          context: ${{inputs.name_service}}
          file: Dockerfile
          push: true
          tags: ${{secrets.REGISTRY_URL}}/kltn/${{inputs.name_service}}:${{github.sha}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  security_check:
    name: Security check for ${{inputs.name_service}}
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Scan security for ${{inputs.name_service}} docker image
        id: generate-report
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{secrets.REGISTRY_URL}}/kltn/${{inputs.name_service}}:${{github.sha}}
          severity: 'HIGH'
          exit-code: 1
          format: template
          template: 'contrib/html.tpl'
          output: user-service-report-${{github.sha}}.html
        env:
          TRIVY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
          TRIVY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}
      - name: Upload ${{inputs.name_service}} security report to artifact tab
        if: always()
        uses: actions/upload-artifact@v4.3.4
        with:
          name: user-service-report-${{github.sha}}.html
          if-no-files-found: warn
          path: user-service-report-${{github.sha}}.html

