on:
  push:
    paths:
      - "user-svc/**"
  pull_request:
    paths:
      - "user-svc/**"
jobs:
  push:
    name: user-svc-push
    if: github.event_name == 'push'
    uses: ./.github/workflows/ci-push-template.yaml
    with:
      SERVICE_NAME: gateway-svc
      SERVICE_PORT: 8001
    secrets: inherit
  pr:
    name: user-svc-pr
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/ci-pr-template.yaml
    with:
      SERVICE_NAME: user-svc
      SERVICE_PORT: 8002
    secrets: inherit